### ISSUE TITLE
How does one install the command line tool?

### ISSUE THREAD

**Issue by AlexVPopov** [tokland/yaml2csv#7]
I install the gem via `gem install yaml2csv`. However, when I do `yaml2csv_conv` I get `zsh: command not found: yaml2csv_conv`. Should I go to the install directory of the gem and invoke it from the `bin` directory there or can I make it available globally?

**Comment by tokland** [comment]
I don't use this package anymore, go ahead creating the missing infrastructure (Gemfile, gemspec and so on), I'll happily merge your PR if it works for you.

**Comment by AlexVPopov** [comment]
:+1:
